name: Deployment Golang Auto Scale

on:
  workflow_dispatch:
  push:
    brances:
      main

env: 
  PORT: ${{ vars.PORT }}

jobs: 
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4 

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set the TAG value
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)
          TAG="version-$CURRENT_DATE"
          TEMPLATE_NAME="go-go-autoscale1-autoscale-cicd-$CURRENT_DATE"
          echo $TEMPLATE_NAME
          echo "TAG=$TAG" >> $GITHUB_ENV  # Set TAG as an environment variable
          echo "TEMPLATE_NAME=$TEMPLATE_NAME" >> $GITHUB_ENV  # Set TAG as an environment variable

      - name: Build Docker image
        run: |
          docker buildx --build-arg PORT=$PORT -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/go-autoscale:$TAG .
      
      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/go-autoscale:$TAG

      - name: Create instance template based on docker image
        run: |
          gcloud compute instance-templates create-with-container $TEMPLATE_NAME \
            --container-image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/go-autoscale:$TAG \
            --region=asia-southeast2 \
            --network-interface=network=bab-lb-network,subnet=lb-jakarta \
            --tags=allow-ssh,lb-backend \
            --machine-type=n1-standard-1 

      - name: Update managed instance group
        run: |
          gcloud compute instance-groups managed rolling-action start-update go-autoscale1-group-autoscale-cicd-v3 \
            --version=template=$TEMPLATE_NAME \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --max-unavailable=1 \
            --replacement-method=recreate \
            --zone=asia-southeast2-a 